name: Smart Merge Agent

on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  smart-merge:
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_PAT }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config user.name "merge-bot"
          git config user.email "raghut44@gmail.com"
          
      - name: Install OpenAI Python SDK
        run: pip install openai==1.14.0
      - name: Install OpenAI Groq SDK
        run: pip install groq
        
      - name: Merge release into develop
        run: |
          git checkout main
          git pull origin main
          git merge origin/release || true
          
      - name: Identify conflicted files
        run: |
          git status --porcelain | grep '^UU' | awk '{print $2}' > conflicted.txt || true
          echo "Conflicted files:"
          cat conflicted.txt

      - name: Create auto-merge-release branch (non-conflicted files)
        run: |
          git checkout -b auto-merge-release
          for file in $(cat conflicted.txt); do
            git restore --staged "$file"
            git restore "$file"
          done
          git add -u
          git commit -m "Auto-merged non-conflicted files from release"
          git push origin auto-merge-release
      - name: Prepare for conflict-merge-release branch (conflicted files)
        run: |
          git checkout main
          git pull origin main
          git merge origin/release || true  # allow merge to continue even if conflicts
          cp -r . ../conflict-copy
          mkdir auto-merge
          git diff --name-only --diff-filter=U > ../conflicts.txt || true

      - name: Resolve conflicts using OpenAI and push conflicts
        run: python3 .github/scripts/resolve_conflicts.py
        
      - name: 💻 Install GitHub CLI
        run: |
          type -p curl >/dev/null || sudo apt install curl -y
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | \
            sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) \
            signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] \
            https://cli.github.com/packages stable main" | \
            sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y


      - name: Create PRs using GitHub CLI
        run: |
          gh pr create --title "Auto Merge: release → develop (no conflicts)" --body "Auto merged non-conflicted files" --head auto-merge-release --base main
          gh pr create --title "AI Merge: release → develop (resolved conflicts)" --body "AI resolved conflicted files from release to develop" --head conflict-merge-release --base main
