name: Smart Merge Agent

on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  smart-merge:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.GROQ_API_KEY }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config user.name "merge-bot"
          git config user.email "raghut44@gmail.com"
          
      - name: Install OpenAI Python SDK
        run: pip install openai==1.14.0
      - name: Install OpenAI Groq SDK
        run: pip install groq
        
      - name: Create merge branches
        run: |
          git checkout main
          git pull origin main
          git merge origin/release || true
          cp -r . ../conflict-copy
          mkdir auto-merge
          git diff --name-only --diff-filter=U > ../conflicts.txt || true
          git checkout -b auto-merge-release
          git add .
          git diff --cached --quiet || git commit -m "Auto-merged release (no conflicts)"
      - name: Push auto-merge branch
        run: |
          git push origin auto-merge-release --force


      - name: Resolve conflicts using OpenAI and push conflicts
        run: python3 .github/scripts/resolve_conflicts.py
        
      - name: Install GitHub CLI
        uses: cli/gh-action@v2

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      - name: Create PRs using GitHub CLI
        run: |
          gh pr create --title "Auto Merge: release → develop (no conflicts)" --body "Auto merged non-conflicted files" --head auto-merge-release --base develop
          gh pr create --title "AI Merge: release → develop (resolved conflicts)" --body "AI resolved conflicted files from release to develop" --head conflict-merge-release --base develop
